[package]
name = "bms_rust"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "console"
path = "src/main_console.rs"

[dependencies]
yew = { version = "0.20", features = ["csr"] }
wasm-bindgen = "0.2.100"
gloo = "0.5"
